"LR": 2.5e-4
"NUM_ENVS": 256
"NUM_STEPS": 512
"TOTAL_TIMESTEPS": 3e8
"EVAL_TIMESTEPS": 2.5e7  # TODO move to just using eval freq (as it's used by plr)
"EVAL_FREQ": 50
"NUM_CHECKPOINTS": 4
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.04
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.0
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
#"ACTIVATION": "relu"
"FC_DIM_SIZE": 512
"HIDDEN_SIZE": 512
"ANNEAL_LR": True
"USE_ROBUST_PLR": False
"USE_LAYER_NORM": False
"LAMBDA_SCHEDULE": False
"LOG_DORMANCY": True